name: Deploy FastAPI Application

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python (latest stable version)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy repository to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: "."
          target: "/var/www/paper_scrapper"

      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          debug: true
          port: 22
          script: |
            cd /var/www/paper_scrapper
            source venv/bin/activate
            # Upgrade pip to the latest version
            pip install --upgrade pip
            # Install requirements
            pip install -r requirements.txt
            # Start the FastAPI application with Uvicorn in the background
            uvicorn api:app --host 0.0.0.0 --port 5001 &

      - name: Wait for deployment to complete
        run: sleep 10 # Adjust the sleep duration as needed
