name: Deploy FastAPI Application

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy repository to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: "."
          target: "/var/www/paper_scrapper"

      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          debug: true
          port: 22
          script: |
            cd /var/www/paper_scrapper
            source venv/bin/activate
            pip install -r requirements.txt
            # Add any other necessary commands like database migrations
            sudo systemctl restart paper_scrapper  # Assuming you have a systemd service setup
