name: Development Build, Test, and Debug

on:
  push:
    branches:
      - development

permissions:
  contents: write
  pull-requests: write

jobs:
  build-test-and-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout development branch
        uses: actions/checkout@v2
        with:
          ref: development

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Log Git Status and Branches
        run: |
          echo "Current branch:"
          git branch -avv
          echo "Remote branches:"
          git branch -r
          echo "Last 3 commits on development:"
          git log -3

      - name: Compare with Main
        run: |
          git fetch origin main:main
          echo "Comparing development with main..."
          git diff --name-status development..main

      - name: Checkout Main and Log
        run: |
          git checkout main
          echo "Last 3 commits on main:"
          git log -3

      - name: Create Debug Branch from Main
        run: |
          git checkout -b debug-branch-${{ github.run_id }} main
          echo "Debug branch created from main"

      - name: Merge Development into Debug Branch and Log
        run: |
          git merge development --no-commit --no-ff
          echo "Changes to be merged from development to debug branch:"
          git diff --name-status --cached

      - name: Final Repository Status
        run: |
          echo "Final Git Status:"
          git status
          echo "All local branches:"
          git branch -avv
