name: Development Build, Test, and Merge

on:
  push:
    branches:
      - development

permissions:
  pull-requests: write  # Grants permission to create pull requests

jobs:
  build-test-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Replace with your actual test command, e.g., pytest
          echo "Running tests!"
      
      - name: Setup GitHub CLI
        run: |
          sudo apt update && sudo apt install -y gh  # Installs the GitHub CLI

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses the built-in GITHUB_TOKEN for authentication
        run: |
          gh auth setup-git  # Configures git to use 'gh' as a credential helper

      - name: Create or Update Pull Request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }  # Defines a function to create or update a PR
          gh_pr_up --title "My pull request" --body "Description"  # Uses the function to create/update a PR
