name: Development Build, Test, and Merge

on:
  push:
    branches:
      - development

permissions:
  contents: write
  pull-requests: write  # Grants permission to create pull requests

jobs:
  build-test-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Using the latest version of actions/checkout

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Replace with your actual test command, e.g., pytest
          echo "Running tests!"

      # Make any changes here that the pull request should include

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated changes by build and test workflow"
          title: "Automated PR: Merging Development changes into Main"
          body: |
            This is an automated pull request to merge changes from the development branch into the main branch.
          branch: "auto-merge-to-main-${{ github.run_number }}"
          base: "main"
          labels: "automerge"
